package com.example.generationckmm.android.utils


const val CLEAR_COLOR_BUTTON_TAG = "CLEAR_COLOR_BUTTON_TAG"
const val CLEAR_PRICE_BUTTON_TAG = "CLEAR_PRICE_BUTTON_TAG"
const val SEARCH_BUTTON_TAG = "SEARCH_BUTTON_TAG"
const val COLOR_TEXT_TAG = "COLOR_TEXT_TAG"
const val PRICE_TEXT_TAG = "PRICE_TEXT_TAG"


const val BRAND_TAG = "BRAND_TAG"
const val PLATE_NUMBER_TAG = "PLATE_NUMBER_TAG"
const val PRICE_AND_COLOR_TAG = "PRICE_AND_COLOR_TAG"
